### ISSUE TITLE
cannot compile ext 

### ISSUE THREAD

**Issue by 742362144** [utah-scs/splinter#27]
I am a rust beginer,  try to run server and have an error:

thread 'main' panicked at 'Failed to load get() extension.', /root/splinter/db/src/master.rs:598:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:519:12
   1: db::master::Master::load_test
             at /root/splinter/db/src/master.rs:598:13
   2: client::main
             at ./src/bin/client/client.rs:632:9
   3: core::ops::function::FnOnce::call_once
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/ops/function.rs:227:5

I use ext/safe-compile to compile extend.

~/splinter/ext# ./safe-compile get get
Compiling src/lib.rs for get target into target/get/deps/libget.so
ERROR: All extensions must include #![no_std]; extensions must only use modules exposed through the sandstorm crate.

plz help me, verrrrry thanks. : )

**Comment by 742362144** [comment]
I notice the bash file splinter/ext/safe-compile contains 'sandstorm' not splinter, maybe that cause error?
